version: "3.9"

services:
  openwebui:
    container_name: openwebui
    build:
      context: ./open-webui
      dockerfile: Dockerfile
    ports:
      - "${OPENWEBUI_PORT:-8080}:8080"
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ./openwebui-data:/app/backend/data
    restart: unless-stopped
