version: "3.8"

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command: >-
      etcd -advertise-client-urls http://0.0.0.0:2379 \
           -listen-client-urls http://0.0.0.0:2379 \
           -listen-peer-urls http://0.0.0.0:2380 \
           -initial-advertise-peer-urls http://0.0.0.0:2380 \
           -initial-cluster etcd=http://0.0.0.0:2380
    volumes:
      - etcd_data:/etcd
    ports:
      - "2379:2379"

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: minio
    command: server /minio_data --console-address :9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/minio_data
    ports:
      - "9000:9000"
      - "9001:9001"

  milvus:
    image: milvusdb/milvus:v2.4.8
    container_name: milvus
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MILVUS_LOG_LEVEL=info
    command: ["milvus", "run", "standalone"]
    depends_on:
      - etcd
      - minio
    ports:
      - "19530:19530"   # GRPC
      - "9091:9091"     # HTTP
    volumes:
      - milvus_data:/var/lib/milvus

  rag-api:
    build: ./rag_api
    container_name: rag-api
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - MILVUS_COLLECTION_NAME=documents
      - EMBEDDING_MODEL_NAME=sentence-transformers/all-MiniLM-L6-v2
      - DOC_CHUNK_SIZE=800
      - DOC_CHUNK_OVERLAP=100
      - LOG_LEVEL=info
    volumes:
      - ./data:/data
    depends_on:
      - milvus
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    environment:
      - WEBUI_AUTH=False
      # Configure your LLM provider in the UI after startup (OpenAI/Ollama/etc.)
    volumes:
      - openwebui_data:/app/backend/data
    ports:
      - "8080:8080"
    depends_on:
      - rag-api

volumes:
  etcd_data:
  minio_data:
  milvus_data:
  openwebui_data:
